Исправление замечаний по рефакторингу 2.0
SenorPomidor/tank-software-design pull request #3
Opened 2023-09-28 19:32 UTC by SenorPomidor

2023-09-29 15:41 UTC, iagoshkov requested changes

2023-09-29 15:41 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/controller/enums/Direction.java
> +public enum Direction implements Action {
Вот у вас нарушение DIP.
Абстракция Direction знает о Keys.
А если мы захотим пять кнопок и ещё джойстик, чтобы управлять танком, их сюда добавлять тоже?

2023-09-29 15:41 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/entity/Tank.java
> +                    .filter(object -> collides(destinationCoordinates, object.getCoordinates()))
Танк начал зависеть от GdxGameUtils.
Нарушение DIP.

2023-09-29 15:41 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/entity/Tank.java
> +        movementProgress = continueProgress(movementProgress, deltaTime, MOVEMENT_SPEED);
Тут опять нарушение DIP.
continueProgress  находится в GdxGameUtils

2023-09-29 15:41 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/entity/interfces/TankEntity.java
> +    void updateState(float deltaTime);
Почему updateState только у TankEntity. А самолёт мы как добавлять будем?

2023-09-29 15:41 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/level/GameLevel.java
> +        tankEntities.add(tank);
А почему tankEntities?
Нарушен OCP.
Куда самолёты добавлять?

2023-09-29 15:41 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/level/GameLevel.java
> +    public void addTank(Tank tank) {
Почему add Tank?
Для самолётов будем делать новый метод addAircraft?
Нарушен OCP.

2023-09-29 15:41 UTC, iagoshkov commented on src/main/java/ru/mipt/bit/platformer/level/GameLevel.java
> +            tank.updateTankMovement(inputController.getTriggeredAction(), gameEntities, deltaTime);
Так и не понял, как мне сюда стрельбу то добавить по кнопке пробел. Опять OCP нарушен.

2023-09-30 13:37 UTC, SenorPomidor commented on src/main/java/ru/mipt/bit/platformer/level/GameLevel.java
> +            tank.updateTankMovement(inputController.getTriggeredAction(), gameEntities, deltaTime);
Я немного поменял логику с клавишами. Добавил метод для стрельбы для наглядности при нажатии на пробел

2023-09-30 13:38 UTC, SenorPomidor commented on src/main/java/ru/mipt/bit/platformer/level/GameLevel.java
> +    public void addTank(Tank tank) {
Сделал что-то общее

2023-09-30 13:38 UTC, SenorPomidor commented on src/main/java/ru/mipt/bit/platformer/level/GameLevel.java
> +        tankEntities.add(tank);
Сделал что-то общее

2023-09-30 13:38 UTC, SenorPomidor commented on src/main/java/ru/mipt/bit/platformer/entity/interfces/TankEntity.java
> +    void updateState(float deltaTime);
Изменил название класса, теперь не должно возникать вопросов

2023-09-30 13:39 UTC, SenorPomidor commented on src/main/java/ru/mipt/bit/platformer/entity/Tank.java
> +        movementProgress = continueProgress(movementProgress, deltaTime, MOVEMENT_SPEED);
Подправил

2023-09-30 13:39 UTC, SenorPomidor commented on src/main/java/ru/mipt/bit/platformer/entity/Tank.java
> +                    .filter(object -> collides(destinationCoordinates, object.getCoordinates()))
Подправил

2023-09-30 13:43 UTC, SenorPomidor commented on src/main/java/ru/mipt/bit/platformer/controller/enums/Direction.java
> +public enum Direction implements Action {
Теперь данная абстракция не знает о Keys, если я правильно вас понял
Для того, чтобы добавить пятую кнопку, для движения - нужно добавить новое значение в Direction (сейчас он называется по-другому)
Для того, чтобы добавить джойстик - нужно создать новый класс, интерфейс и изменить InputController, чтобы отслеживать нажатие кнопок на джойстике

2023-10-08 11:21 UTC, iagoshkov approved these changes
Давайте вмержим это, я уже не пойму, где ваши изменения, тут они что-то не показываются.

2023-10-08 12:59 UTC, merged